### ISSUE TITLE
Switch to setuptools_scm for versioning

### ISSUE THREAD

**Issue by JohnPaton** [JohnPaton/airbase#18]
- [ ] Switch to using `setuptools_scm` for the package versioning
- [x] CI should release to PyPI on any new tag (#13)
- [ ] Should start writing a `__version__.py` (or similar) inside the package for easily checking the version from Python

**Comment by avaldebe** [comment]
Why `setuptools_scm`? 

You can define the version on `setup.cfg`/`setup.py` and access it on the program with `importlib.metadata.version`. 

The docs configuration uses `importlib.metadata.version` to determine the release and version strings.

https://github.com/JohnPaton/airbase/blob/aece27fe17db7beaa094d2c04f3a4a1d6c72259f/docs/source/conf.py#L16-L19

https://github.com/JohnPaton/airbase/blob/aece27fe17db7beaa094d2c04f3a4a1d6c72259f/docs/source/conf.py#L37-L41

following this pattern you can define `__version__` in `__init__.py`  (or `__version__.py`)

``` python
if sys.version_info >= (3, 8):
    from importlib import metadata
else:
    import importlib_metadata as metadata

__version__ = metadata.version(__package__)
```

**Comment by JohnPaton** [comment]
fair enough about the `__version__.py`. `setuptools_scm` builds distributions that are versioned according to the git history, so you just need to push tags instead of actually modifying your code anywhere to type the version manually.

**Comment by avaldebe** [comment]
> `setuptools_scm` builds distributions that are versioned according to the git history, so you just need to push tags instead of actually modifying your code anywhere to type the version manually.

I see. Do you want me to add this to #19?

**Comment by JohnPaton** [comment]
It's okay, we can do it seperately. This cleanup stuff doesn't require a release anyway so no rush
