### ISSUE TITLE
Add cli for downloading

### ISSUE THREAD

**Issue by JohnPaton** [JohnPaton/airbase#30]
This can basically be a 1-1 map from #29 to a command line interface, to avoid needing to write any code to start downloading.

**Comment by avaldebe** [comment]
Hi @JohnPaton 

For work I'll build a CLI around `airbase` to download all stations for the current year.
I would not mind to extend it into a full PR for this issue.

Are you interested?

**Comment by avaldebe** [comment]
so far my prototype CLI looks like

```
$ airbase --help
Usage: airbase [OPTIONS]

  Download Air Quality Data from the European Environment Agency (EEA)

Options:
  --path PATH     [default: data]
  --year INTEGER  [default: 2022]
  -V, --version
  --help          Show this message and exit.
```

**Comment by JohnPaton** [comment]
I am definitely interested! The timing is a bit tricky as I'm about to go on a long holiday but let me take a look at the PR, thanks so much for contributing again.

**Comment by JohnPaton** [comment]
imo yes!
