### ISSUE TITLE
PyPI release action needs verified email address

### ISSUE THREAD

**Issue by avaldebe** [JohnPaton/airbase#51]
@JohnPaton 
looks like PyPI increased the security since the last release,
which caused the release of a new version from CI to fail

```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         User 'johnpaton' does not have a verified primary email address. Please
         add a verified primary email before attempting to upload to PyPI. See  
         https://pypi.org/help/#verified-email for more information.    
```
https://github.com/JohnPaton/airbase/actions/runs/9676343872/job/26695754041#step:7:29

**Comment by JohnPaton** [comment]
Thanks for the heads up! I've taken care of this, 0.8 is published
